### ISSUE TITLE
Inappropriate use of the arduino GitHub topic

### ISSUE THREAD

**Issue by per1234** [esimkowitz/Particle-Adafruit-MCP23008#1]
The code in this repository is not compatible with the Arduino IDE (in fact, [you went out of your way to break compatibility with the Arduino IDE](https://github.com/esimkowitz/Particle-Adafruit-MCP23008/commit/90ff56183dedd9feee26a1d530a1e453e8766bed)) so it's not appropriate to use the `arduino` GitHub topic.

The topic can be removed by clicking the "Manage topics" link near the top of the repository's home page and then clicking the **X** to the right of `arduino`.

**Comment by esimkowitz** [comment]
I’m hesitant to make this change as I believe there are a lot of people who do not understand the difference between Particle and Arduino IDEs. I would hate for someone to be looking for a Particle library and be unable to find it. What is your reference for the use of the Arduino topic?

**Comment by per1234** [comment]
If they don't understand the difference then they're going to be having trouble no matter what. A much larger problem is the Arduino IDE users who end up in a lot of confusion after trying to use a library advertised as "Arduino" that actually is not. This is spam, plain and simple.

You started with a library that was Arduino compatible and intentionally broke it, even though you could have simply added Particle compatibility while retaining Arduino support. It's likely you could have even gotten the changes merged back to the parent repository since Adafruit sells Particle boards. This whole fragmentation between Arduino and Particle is completely unnecessary and harmful to both communities.

**Comment by esimkowitz** [comment]
Because of the required structure of a Particle repository, this backwards-compatibility is tricky. I agree that this is a problem that I hope the community can solve. I am removing the tags from my repositories.
